<style>
    #overlay{position:fixed;top:0;z-index:11111;width:100%;height:100%;display:none;background:rgba(0,0,0,.6)}
    .cv-spinner{height:100%;display:flex;justify-content:center;align-items:center}
    .spinner{width:30px;height:30px;border:4px solid #ddd;border-top:4px solid #2e93e6;border-radius:50%;animation:.8s linear infinite sp-anime}@keyframes sp-anime{100%{transform:rotate(360deg)}}
</style>
<div id="overlay">
    <div class="cv-spinner">
        <span class="spinner"></span>
    </div>
</div>