<style>
    #contact-email,#contact-message,#contact-subject,#full-name{width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;box-sizing:border-box;margin-top:6px;margin-bottom:16px;resize:vertical}
    button[type=submit]{background-color:#046cf1;color:#fff;padding:12px 20px;border:none;border-radius:4px;cursor:pointer}
    button[type=submit]:hover{background-color:#1a7efb}.contact-section{border-radius:5px}.first-contact{display:flex}
    .contact-name{width:50%;margin-right:10px}.contact-email{width:50%;margin-left:10px}
    #contact-email:focus,#contact-message:focus,#contact-subject:focus,#full-name:focus{background-color:#fff;border-color:#1a7efb;color:#606266;outline:0}
    label:after{color:#f56c6c;content:" *";margin-left:3px}.contact-response{color:#0b8311;font-weight:500;margin-bottom:15px}
    .contact-title{margin-bottom:20px}@media only screen and (max-device-width:480px){.first-contact{display:block}.contact-email,.contact-name{width:100%;margin:0}}
</style>

    <div class="contact-section">
        <?php if (!isset($_COOKIE["contact-email-is-sent"])): ?>
            <p class="contact-title"><?= __('To get in touch with us, please fill in the information below:', 'email-maketting')?></p>
            <p class="contact-response"></p>
            <div class="contact-form">
                <form class="form-contact" id="form-contact">
                    <div class="first-contact">
                        <div class="contact-name">
                            <label for="full-name"><?= __('Full Name', 'email-maketting')?></label>
                            <input type="text" id="full-name" name="name" placeholder="<?= __('Your name..', 'email-maketting')?>" required>
                        </div>
                        <div class="contact-email">
                            <label for="email"><?= __('Email', 'email-maketting')?></label>
                            <input type="email" id="contact-email" name="email" placeholder="<?= __('Your email..', 'email-maketting')?>" required>
                        </div>
                    </div>

                    <div class="contact-subject">
                        <label for="subject"><?= __('Subject', 'email-maketting')?></label>
                        <input type="text" id="contact-subject" name="subject" placeholder="<?= __('Subject', 'email-maketting')?>" required>
                    </div>

                    <div class="contact-message">
                        <label for="message"><?= __('Content', 'email-maketting')?></label>
                        <textarea id="contact-message" name="message" placeholder="Write something.." style="height:200px" required></textarea>
                    </div>

                    <div class="submit-request">
                        <button type="submit" id="submit-request" value="Submit"><?= __('Submit','email-maketting')?></button>
                    </div>
                </form>
            </div>
        <?php else: ?>
            <p class="contact-response"><?= __('Thank you for reaching out. We have received your message and will respond to you as soon as possible.', 'email-maketting')?></p>
        <?php endif;?>
    </div>

